### PR TITLE
Fix #4.

### LINKED ISSUE #4: Explicitly run `bash` on Linux so `read` is guaranteed to be used
Opening a new issue from the conversation started in #1.

Probably the least invasive fix would be to encapsulate the `read` call in `bash -c ""`. (Just need to be careful when escaping that string.)

### PR DESCRIPTION
**Pull request by jfcherng**

### CODE REVIEW

**Comment by joeyespo** [comment]
Thanks, @jfcherng!

**Comment by jfcherng** [comment]
You are welcome :)

**Comment by joeyespo** [comment]
Btw, just added you to [AUTHORS.md](https://github.com/joeyespo/sublimetext-console-exec/blob/master/AUTHORS.md). Thanks again!

**Comment by jfcherng** [comment]
Moved https://github.com/joeyespo/sublimetext-console-exec/issues/6

**Comment by joeyespo** [comment]
@jfcherng Perhaps open a new issue and ask there. Otherwise this one will get kind of noisy :-)

**Pull request merged**
